sudo: required
services:
  - docker

before_install:
  - docker build -t lotahen/docker-react -f Dockerfile.dev .

script:
  - docker run lotahen/docker-react npm run test:CI -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-447834613359"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"